apiVersion: v1
kind: Service
metadata:
  name: case-bry-starlord
spec:
  selector:
    app: case-bry-starlord
  type: NodePort
  ports:
  - name: http
    port: 8501
    targetPort: 8501
    nodePort: 30080